### ISSUE TITLE
watch-button registers more than one button press from time to time

### ISSUE THREAD

**Issue by jbl0ndie** [Pidee/libpidee#5]
@rc1 Is this a hardware issue, do you think?
`./watch-button`

Press button and release it multiple times. Instances of repeat presses are noted with *

```
button pressed
button released
button pressed *
button pressed *
button released
button pressed
button released *
button released *
button pressed *
button pressed *
button pressed *
button released
button pressed
button released
button pressed
button released
button pressed
button released
button pressed
button released
button pressed
button released
```

**Comment by rc1** [comment]
It might be bouncing. We could try and play with the [edge binding](https://github.com/Pidee/libpidee/blob/master/src/libpidee.h#L107) by setting it to something different as mentioned [here](http://wiringpi.com/reference/priority-interrupts-and-threads/).

**Comment by jbl0ndie** [comment]
Perhaps we should have debounced. It's stale now so I'm closing this.

**Comment by jbl0ndie** [comment]
Perhaps we should have debounced. It's stale now so I'm closing this.
